# Generated by Django 4.1.5 on 2023-01-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartbook',
            old_name='count_item',
            new_name='count_books',
        ),
    ]
