# Generated by Django 4.1.5 on 2023-01-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='count_books',
        ),
    ]
