# Generated by Django 4.1.5 on 2023-01-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/authors/', verbose_name='Изображение'),
        ),
    ]
